version: '3.3'

secrets:
    tls-crt:
        external: true
    tls-key:
        external: true

services:
    nginx:
        image: nginx:1.25.2
        restart: always
        ports:
            - 443:443
            - 80:80
        secrets:
            - tls-crt
            - tls-key
        volumes:
            - type: bind
              source: ./nginx.conf
              target: /etc/nginx/nginx.conf
        deploy:
            placement:
                constraints:
                    - node.hostname==agent2

    ssr:
        image: '${ABTESTING_IMAGE}'
        environment:
            - PORT=3000
        deploy:
            replicas: 3
