name: PR checks

on:
    pull_request:
        branches:
            - master

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - runs: npm install
            - name: Prettify
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write **/*.{js,md}
                  only_changed: True
                  prettier_plugins: 'prettier-plugin-svelte'
