name: PR checks

on:
    pull_request:
        branches:
            - master

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - run: npm install
            - name: Prettify
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write .
                  only_changed: True
