name: PR checks

on:
    pull_request:
        branches:
            - master

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - run: npm install
            - run: npx prettier --check `git diff --name-only master..`
