name: PR checks

on:
    pull_request:
        branches:
            - master

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - run: npm install
            - run: npx prettier --check `git diff --name-only origin/master..${{ github.head_ref }}`
    typescript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - run: npm install
            - run: npx svelte-check
    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - run: npm install
            - run: npx eslint --ext .ts,.js,.tsx,.jsx,.svelte .
